site_name: Libbitcoin Docs
copyright: MIT
theme:
  name: material
  logo: assets/libbitcoin-logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: navy
      accent: navy
      toggle:
        icon: material/toggle-switch
        name: Dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: navy
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode

nav:
  - Introduction: Introduction.md
  - About: about.md
  - FAQ: FAQ.md
  - Guides: 
    - Running Libbitcoin:
      - Download & Install: guides/RunningLibbitcoin/Download&Install.md
      - Build From Source: guides/RunningLibbitcoin/BuildFromSource.md
      - Configuration Options: guides/ConfigurationOptions.md
    - Electrum: guides/Electrum.md
  - Libbitcoin-build:
          - Intro: libbitcoin-build/intro.md
  - Libbitcoin-client:
          - Intro: libbitcoin-client/intro.md
  - Libbitcoin-database:
          - Intro: libbitcoin-database/intro.md
  - Libbitcoin-explorer:
          - Intro: libbitcoin-explorer/intro.md
          - Commands: libbitcoin-explorer/commands.md
  - Libbitcoin-network:
          - Intro: libbitcoin-network/intro.md
  - Libbitcoin-node:
          - Intro: libbitcoin-node/intro.md
  - Libbitcoin-protocol:
          - Intro: libbitcoin-protocol/intro.md
  - Libbitcoin-server:
          - Intro: libbitcoin-server/intro.md
  - Libbitcoin-system:
          - Intro: libbitcoin-system/intro.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  version:
    provider: mike

extra_javascript:
  - https://kit.fontawesome.com/090ca49637.js
  - js/external-links.js

extra_css:
  - css/external-links.css
  - css/blockquote-cite.css
