site_name: Libbitcoin Docs
copyright: MIT
theme:
  name: material
  logo: assets/libbitcoin-logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: navy
      accent: navy
      toggle:
        icon: material/toggle-switch
        name: Dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: navy
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode

nav:
  - Introduction: index.md
  - About: about.md
  - FAQ: FAQ.md
  - Guides: 
    - Running Libbitcoin:
      - Run Binaries: section1/subsection/page3.md
      - Build Source: section1/subsection/page3.md
      - Configuration Options: section1/subsection/page3.md
    - Connect Electrum: section1/subsection/page3.md
  - Libbitcoin-blockchain:
          - Page 1: section1/subsection/page3.md
  - Libbitcoin-build:
          - Page 1: section1/subsectionA/page1.md
          - Page 2: section1/subsectionA/page2.md
  - Libbitcoin-client:
          - Page 3: section1/subsectionB/page3.md
  - Libbitcoin-consensus:
          - Page 3: section1/subsectionB/page3.md
  - Libbitcoin-database:
          - Page 3: section1/subsectionB/page3.md
  - Libbitcoin-explorer:
          - Page 3: section1/subsectionB/page3.md
  - Libbitcoin-network:
          - Page 3: section1/subsectionB/page3.md
  - Libbitcoin-node:
          - Page 3: section1/subsectionB/page3.md
  - Libbitcoin-protocol:
          - Page 3: section1/subsectionB/page3.md
  - Libbitcoin-server:
          - Page 3: section1/subsectionB/page3.md
  - Libbitcoin-system:
          - Page 3: section1/subsectionB/page3.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  version:
    provider: mike

extra_javascript:
  - https://kit.fontawesome.com/090ca49637.js
  - js/external-links.js

extra_css:
  - css/external-links.css
  - css/blockquote-cite.css
